const ADD_ERROR = "ADD_ERROR";
const REMOVE_ERROR = "REMOVE_ERROR";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const LOAD_MESSAGES = "LOAD_MESSAGES";
const REMOVE_MESSAGE = "REMOVE_MESSAGE";
const ADD_MESSAGE = "ADD_MESSAGE";

export {
  ADD_ERROR,
  REMOVE_ERROR,
  SET_CURRENT_USER,
  LOAD_MESSAGES,
  REMOVE_MESSAGE,
  ADD_MESSAGE
};
